dashboard/urls.py
from django.urls import path

from . import views, ajax_views

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('setting/', views.Setting.as_view(), name='setting'),
    path('invite/', views.Invite.as_view(), name='invite'),
    path('invite/history/', views.InviteHistory.as_view(), name='invite_history'),
    path('purchase/', views.Purchase.as_view(), name='purchase'),
    path('transactions/', views.Transactions.as_view(), name='transactions'),
]

# AJAX url
urlpatterns += [
    path('ajax/tag/add', ajax_views.AddTag.as_view(), name='ajax_tag_add'),
    path('ajax/tag/get/all', ajax_views.GetTags.as_view(), name='ajax_tag_get_all'),
    path('ajax/tag/remove/<int:tag_id>', ajax_views.RemoveTag.as_view(), name='ajax_tag_remove'),
    path('ajax/contact/get/all', ajax_views.GetContact.as_view(), name='ajax_contact_get_all'),
    path('ajax/contact/remove/<str:contact_id>', ajax_views.RemoveContact.as_view(), name='ajax_contact_remove'),
    path('ajax/contact/add', ajax_views.AddContact.as_view(), name='ajax_contact_add'),
    path('ajax/tag/get/all/select2', ajax_views.GetTagSelect2.as_view(), name='ajax_tag_get_all_select2'),
    path('ajax/user/get/all/select2', ajax_views.GetContactSelect2.as_view(), name='ajax_contact_get_all_select2'),
    path('ajax/invition/add', ajax_views.CreateInviteCard.as_view(), name='ajax_create_invition'),
    path('ajax/invition/get/all', ajax_views.GetInvititon.as_view(), name='ajax_get_invition_all'),
]

invitation/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.admin import admin_site
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from dashboard.views import show_invite_card

urlpatterns = [
    path('', RedirectView.as_view(url='panel/', permanent=False), name='index'),
    path('admin/', admin_site.urls),
    path('panel/', include('dashboard.urls')),
    path('auth/', include('authentication.urls')),
    path('payment/', include('payment.urls')),
    path('invite/<uuid:card_id>', show_invite_card, name='show_invite_card'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from os import name
from django.urls import path

from . import views, ajax_views

app_name = 'payment'
urlpatterns = [
    path('verify', views.verify, name='verify'),
    path('pay/<int:authority>', views.pay, name='pay')
]

urlpatterns += [
    path('ajax/invoice/all', ajax_views.GetInvoice.as_view(), name='ajax_invoice_get_all'),
    path('ajax/invoice/add', ajax_views.CreateInvoice.as_view(), name='ajax_invoice_add')
]

dashboard/models.py
from typing import List, Optional
import uuid
from datetime import datetime

from django.db import transaction
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.utils.timezone import now

from django_mysql.models import Model, base
from django_mysql.models import SetCharField
from jsonschema import Draft7Validator
from jsonschema.exceptions import ValidationError as JsonValidationError

from utils.validators import validate_mobile, validate_draft7, validate_template
from utils.config import CONFIG, THUMBNAIL_DIRECTORY_PATH, TEMPLATE_DIRECTORY_PATH
from utils.json_validation import generate_validator_darft7


User = get_user_model()

class BasicField(Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now=True, verbose_name=_('تاریخ ایجاد'))
    is_deleted = models.BooleanField(default=False, verbose_name=_('آیا حذف شده است؟'))


class Contact(BasicField):
    class Meta:
        verbose_name = _('مخاطب')
        verbose_name_plural = _('مخاطبین')
        index_together = ['owner', 'phone']


    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    first_name = models.CharField(max_length=50, verbose_name=_('نام'), null=True, blank=True)
    last_name = models.CharField(max_length=50, verbose_name=_('نام خانوادگی'), null=True, blank=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, 
                              verbose_name=_('مالک'), related_name='contacts', 
                              null=True, db_index=True)
    phone = models.CharField(max_length=11, validators=[validate_mobile], null=True, verbose_name=_('تلفن همراه'))
    communicative_road = models.JSONField(verbose_name=('راه های ارتباطی'), null=True, blank=True)
    tags = SetCharField(base_field=models.IntegerField(), size=10, max_length=(10*3), 
                        verbose_name=_('تگ'), null=True, blank=True)

    def __str__(self) -> str:
        return self.first_name + ' ' + self.last_name

    @staticmethod
    def get_by_user(user:User):
        return Contact.objects.filter(owner=user).exclude(is_deleted=True)

    @staticmethod
    def sync(contacts: List['Contact']) -> None:
        '''
        check phone number from available social media is registed
        or not
        '''
        # TODO used `bulk_update` https://docs.djangoproject.com/en/3.2/ref/models/querysets/#bulk-update
        ...

    @staticmethod
    def create_contact(first_name:str, last_name:str, user:User,
                       phone, tags:List, communicative_road:dict) -> 'Contact':

        tags = [int(tag) for tag in tags]
        # only user tag can be use
        user_tag = Tag.validate_tags(user, tags)

        contact = Contact(
            first_name=first_name,
            last_name=last_name,
            owner=user,
            phone=phone,
            tags=user_tag,
            communicative_road=communicative_road
        )

        contact.save()
        
        return contact


class Tag(BasicField):
    class Meta:
        verbose_name = _('برچسب')
        verbose_name_plural = _('برچسب ها')
        unique_together = ["owner", "name"]

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, 
                              verbose_name=_('مالک'), related_name='tags', 
                              null=True, db_index=True)
    name = models.CharField(max_length=20, verbose_name=_('نام'), default=_('ندارد'))
    description = models.CharField(max_length=100, verbose_name=_('توضیح'), null=True, blank=True)

    def __str__(self) -> str:
        return self.name

    @staticmethod
    def get_by_user(user:User):
        return Tag.objects.filter(owner=user)
       
    @staticmethod
    def validate_tags(user:User, tags:List) -> set:
        user_tag = set(Tag.get_by_user(user).values_list('id', flat=True))
        user_tag = user_tag.intersection(tags)
        return user_tag


class Template(BasicField):
    class Meta:
        verbose_name = _('قالب')
        verbose_name_plural = _('قالب ها')

    name = models.CharField(max_length=100, verbose_name=_('نام قالب'))
    description = models.CharField(max_length=250, verbose_name=_('توضیحات'))
    # TODO set default thumbnail
    thumbnail = models.ImageField(null=True, blank=True,
                                  upload_to=THUMBNAIL_DIRECTORY_PATH, verbose_name=_('پیش‌نمایش'))
    schema = models.JSONField(validators=[validate_template], verbose_name=_('ساختار'))
    path = models.FileField(verbose_name=_('فایل قالب'), upload_to=TEMPLATE_DIRECTORY_PATH, default='')

    @staticmethod
    def by_id(template_id:int) -> Optional['Template']:
        return Template.objects.filter(pk=template_id).first()
    
    def __str__(self) -> str:
        return self.name + ' | ' + self.description

    def generate_thumbnail(self):
        raise NotImplemented


class Invitation(BasicField):
    class Meta:
        verbose_name = _('دعوت‌نامه')
        verbose_name_plural = _('دعوت‌نامه ها')

    owner = models.ForeignKey(User, verbose_name=_('ایجاد کننده'), on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=150, verbose_name=_('عنوان'), default=_('ندارد'))
    send_at = models.DateTimeField(null=True, blank=True, verbose_name=_('ارسال در تاریخ'))
    informations = models.JSONField(validators=[validate_draft7], verbose_name=_('اطلاعات قالب'))
    template = models.ForeignKey(Template, verbose_name=_('قالب'), on_delete=models.SET_NULL, null=True)
    is_sent = models.BooleanField(default=False, editable=True, verbose_name=_('ارسال شده'))
    extra_data = models.JSONField(null=True, verbose_name=_('اطلاعات اضافی'))

    def __str__(self) -> None:
        return str(self.owner) + ' | ' + self.title

    def save(self, *args, **kwargs):
        # validate information with template schema
        Draft7Validator(generate_validator_darft7(self.template.schema['fields'])).validate(self.informations)
        super().save(*args, **kwargs)

    @property
    def is_scheduler(self) -> bool:
        return bool(self.send_at)

    @property
    def is_information_valid(self) -> bool:
        try:
            Draft7Validator(generate_validator_darft7(self.template.schema['fields'])).validate(self.informations)
            return True
        except JsonValidationError:
            return False


    @staticmethod
    @transaction.atomic
    def create_invitation(user:User, template:Template, information:dict, is_schedule:bool, contacts:List = None, 
                          tags:List = None, send_at:datetime = None, send_sms:bool = False):

        title = information['title']
        del information['title']

        extra_data = {
            'send_sms': send_sms
        }
        
        invitation = Invitation(
            owner=user, 
            template=template, 
            title=title,
            informations=information,
            extra_data=extra_data,
        )

        if is_schedule and send_at:
            invitation.send_at = send_at
        else:
            invitation.send_at = now()
        
        if not invitation.is_information_valid:
            raise ValueError('schema error')
        else:
            invitation.save()

        contact_list = []

        if contacts:
            contact_list += list(Contact.objects.filter(id__in=contacts))
        
        if tags:
            user_contact = Contact.get_by_user(user)
            contact_list += list(user_contact.filter(tags__in=tags))
        
        if send_sms:
            #calcualte cost
            sms_cost = CONFIG['SMS_COST'] * len(contact_list)
            if user.cash >= sms_cost:
                user.cash -= sms_cost
                user.save()
            else:
                raise Exception('more than cash')

        InvitationCard.create_invitation_card(invitation, contact_list)

    @staticmethod
    def get_by_user(user):
        return Invitation.objects.filter(owner=user).exclude(is_deleted=True)


class InvitationCard(BasicField):

    class Meta:
        verbose_name = _('کارت دعوت')
        verbose_name_plural = _('کارت های دعوت')
        index_together = ["invitation", "is_sent"]


    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, db_index=True)
    invitation = models.ForeignKey(Invitation, verbose_name=_('دعوت'), blank=False, 
                                   null=True, on_delete=models.DO_NOTHING, related_name='cards')
    contact = models.ForeignKey(Contact, verbose_name=_('مخاطب'), null=True, 
                                blank=False, on_delete=models.DO_NOTHING)
    is_sent = models.BooleanField(default=False, editable=True, verbose_name=_('ارسال شده'))

    def get_absolute_url(self):
        return reverse('show_invite_card', args=(self.id, )) 

    def __str__(self) -> str:
        return f'{self.contact} | {self.invitation}  | ' + ('ارسال شده' if self.is_sent else 'ارسال نشده')


    @staticmethod
    @transaction.atomic
    def create_invitation_card(invitation:Invitation, contacts:List[Contact]) -> None:
        invitation_card_bunch = []
        for contact in contacts:
            invitation_card_bunch.append(InvitationCard(
                invitation=invitation,
                contact=contact
            ))
        
        InvitationCard.objects.bulk_create(invitation_card_bunch, batch_size=100)

dashboard/forms.py
from django import forms
from django.contrib.auth import get_user_model

class UserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'username', 'phone', 'email')

dashboard/views.py
from django.http.response import Http404, HttpResponse
from dashboard import send_invition
from payment.models import Invoice
import uuid

from django.http.request import HttpRequest
from dashboard.models import InvitationCard, Template, Tag, Contact as ContactModel
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic import View

from .mixins import PremissionMixin
from .forms import UserForm
from utils.upload import save_uploaded_file
from utils.config import CSV_DIRECTORY_PATH, CONFIG
from utils.email import render_to_string


@login_required
def index(request):
    return render(request, 'dashboard/base.html')


def show_invite_card(request, card_id):
    invite_card = InvitationCard.objects.select_related('contact', 'invitation__template')\
                                        .filter(id=card_id)

    if not invite_card.exclude():
        raise Http404
    else:
        invite_card = invite_card.first()

    template_file = open(invite_card.invitation.template.path.path, 'r').read()

    context = {
        **invite_card.invitation.informations,
        'first_name': invite_card.contact.first_name,
        'last_name': invite_card.contact.last_name
    }
    content = render_to_string(template_file, context=context)
    return HttpResponse(content)


class Profile(PremissionMixin, View):

    def get(self, request, *args, **kwargs):
        return render(request, 'dashboard/profile.html',
                      context={'user': request.user})

    def post(self, request, *args, **kwargs):
        form = UserForm(request.POST, instance=self.request.user)
        if form.is_valid():
            form.save()

        return render(request, 'dashboard/profile.html',
                      context={'user': request.user,
                               'errors': form.errors.get_json_data()})


class Contact(PremissionMixin, View):

    def get(self, request, *arg, **kwargs):
        return render(request, 'dashboard/contact_manage.html', context={'csv_sample': 'upload/upload/csv/sample.csv'})

    def post(self, request: HttpRequest, *args, **kwargs):
        path = CONFIG['FILE_UPLOAD_TEMP_DIR'] + '/' + \
            CSV_DIRECTORY_PATH + str(uuid.uuid4())
        save_uploaded_file(path=path, file=request.FILES['file'])

        tags = [int(tag) for tag in request.POST.getlist('tags')]

        tags = Tag.validate_tags(request.user, tags)
        contact_list = []
        with open(path, 'r', encoding="utf8") as f:
            # skip first row
            lines = f.readlines()[1:]
            for line in lines:
                cols = line.split(',')
                first_name = cols[0]
                last_name = cols[1]
                phone = cols[2]
                email = cols[3]
                contact_list.append(ContactModel(
                    first_name=first_name,
                    last_name=last_name,
                    phone=phone,
                    tags=tags,
                    owner=request.user,
                    communicative_road={'email': email}
                ))

        ContactModel.objects.bulk_create(contact_list)

        return render(request, 'dashboard/contact_manage.html')


class Setting(PremissionMixin, View):

    def get(self, request, *arg, **kwargs):
        return render(request, 'dashboard/setting.html')


class Invite(PremissionMixin, View):

    def get(self, request, *args, **kwargs):
        content = {
            'tempaltes': Template.objects.all(),
            'SMS_COST': CONFIG['SMS_COST']
        }
        return render(request, 'dashboard/invite.html', context=content)


class InviteHistory(PremissionMixin, View):

    def get(self, request, *args, **kwargs):
        return render(request, 'dashboard/invite_list.html')


class Purchase(PremissionMixin, View):

    def get(self, request, *args, **kwargs):
        return render(request, 'dashboard/purchase.html')


class Transactions(PremissionMixin, View):

    def get(self, request, *args, **kwargs):
        return render(request, 'dashboard/transactions.html',
                      context={'choices': Invoice.StatusChoices.choices})

dashboard/templates/dashboard/invite_list.html
{% extends 'dashboard/base.html' %}
{% block title %}
{{ block.super }}
دعوت نامه ها
{% endblock %}

{% load dashboard_tag %}
{% load static %}

{% block page_title %}
<h1><i class="fa fa-envelope "></i> دعوت نامه های ایجاد شده</h1>
<p>مشاهد و مدیریت</p>

{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'dashboard/css/persian-datepicker.min.css' %}">
<style>
    *,
    body {
        font-family: Vazir;
    }
</style>
{% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-title-w-btn">
                <h3 class="title">فیلترها</h3>
            </div>
            <div class="tile-body">
                <form id="filterForm">
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label class="control-label">تاریخ</label>
                            <input class="form-control date" type="text">
                            <input type="hidden" name="startDate" id="date-alt">
                        </div>
                    </div>
                </form>
            </div>
            <div class="tile-footer">
                <button class="btn btn-primary" type="button" id="formFilterSubmit"><i
                        class="fa fa-fw fa-lg fa-search"></i>جستجو</button>&nbsp;&nbsp;&nbsp;
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <table class="table table-hover table-bordered" id="invite-table" style="width: 100%;">
                    <thead>
                        <tr>
                            <th>عنوان</th>
                            <th>روز و ساعت </th>
                            <th>تعداد میهمانان</th>
                            <!-- <th>وضعیت</th>
                            <th>عملیات</th> -->
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js%}
<script type="text/javascript" src="{% static 'dashboard/js/plugins/sweetalert.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/utility.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/dropzone.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/select2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/dataTables.bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/persian-datatable.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/persian-date.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/persian-datepicker.min.js' %}"></script>
<script>
    $(() => {
        var inviteTable = $('#invite-table').DataTable({
            paging: true,
            pageLength: 50,
            searching: true,
            fixedColumns: true,
            serverSide: true,
            ajax:{
                url: "{% url 'ajax_get_invition_all' %}",
                data: (data) => {
                    let formData = $('#filterForm').serialize()
                    data = new URLSearchParams({
                        start: data.start,
                        length: data.length,
                        search: data.search.value,
                        csrfmiddlewaretoken: "{{ csrf_token }}"
                    }).toString()
                    return data + '&' + formData
                },
                type: 'POST'
            },
            columns: [
                {
                    data: 'title'
                },
                {
                    data: 'sendAt',
                    render: (date) => {
                        return new Date(date).toLocaleDateString('fa-IR')
                    }
                },
                {
                    data: 'cardCount'
                }
            ],
            language: datatablePersianLang,
        })

        $('.date').persianDatepicker({
            observer: true,
            format: 'YYYY/MM/DD',
            altField: '#date-alt'
        });
    
        $('#formFilterSubmit').click(event => {
            inviteTable.ajax.reload()
        })
    })
</script>
{% endblock %}

dashboard/templates/dashboard/purchase.html
{% extends 'dashboard/base.html' %}
{% block title %}
{{ block.super }}
خرید
{% endblock %}

{% load dashboard_tag %}
{% load static %}

{% block extra_head %}
{% endblock %}

{% block page_title %}
<h1><i class="fa fa-credit-card-alt"></i> خرید</h1>
<p>خرید، افزایش اعتبار و...</p>

{% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-5">
        <div class="tile">
            <div class="tile-title-w-btn">
                <h3 class="title">افزایش اعتبار</h3>
            </div>
            <form method="POST" id="CreateInvoiceForm">
                {% csrf_token %}
                <div class="tile-body">
                    <div class="form-group">
                        <label class="control-label">مبلغ</label>
                        <input class="form-control" type="text" name="amount" 
                            maxlength="20" placeholder="مبلغ مورد نظر خود را به ریال وارد کنید">
                    </div>
                    <div class="form-group">
                        <label>توضیحات</label>
                        <textarea class="form-control" rows="3" name="description" maxlength="100"></textarea>
                    </div>
                </div>
                <div class="tile-footer">
                    <button class="btn btn-primary" type="button" id="submitCreateInvoice"><i
                            class="fa fa-fw fa-lg fa-check-circle"></i>ثبت</button>&nbsp;&nbsp;&nbsp;
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block extra_js%}
<script type="text/javascript" src="{% static 'dashboard/js/plugins/sweetalert.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/utility.js' %}"></script>
<script>
    var CSRF_TOKEN = 'csrfmiddlewaretoken={{csrf_token}}'
</script>
<script>
        $(() => {
            $('#submitCreateInvoice').click(event => {
                payload = formToObject('#CreateInvoiceForm')
                $.ajax({
                    type: 'POST',
                    url: "{% url 'payment:ajax_invoice_add' %}",
                    headers: { 'X-CSRFToken': '{{csrf_token}}' },
                    data: JSON.stringify(payload),
                    dataType: 'json',
                    contentType: 'application/json'
                }).done(data => {
                    window.location.href = data['redirect']
                }).fail(errors => {
                    alert('fail')
                })
            })
        })

        function formToObject(form){
            let data = $(form).serializeArray()
            let formObject = {}

            for (let index = 0; index < data.length; index++) {
                formObject[data[index].name] = data[index].value
            }

            return formObject
        }
</script>
{% endblock %}

dashboard/templates/dashboard/transactions.html
{% extends 'dashboard/base.html' %}
{% block title %}
{{ block.super }}
تراکنش های
{% endblock %}

{% load dashboard_tag %}
{% load static %}

{% block page_title %}
<h1><i class="fa fa-credit-card-alt"></i> تراکنش های انجام شده</h1>
<p>مشاهد و مدیریت</p>

{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'dashboard/css/persian-datepicker.min.css' %}">
<style>
    *,
    body {
        font-family: Vazir;
    }
</style>
{% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-title-w-btn">
                <h3 class="title">فیلترها</h3>
            </div>
            <div class="tile-body">
                <form action="" id="filterForm">
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label class="control-label">از تاریخ</label>
                            <input class="form-control create-date" type="text" >
                            <input type="hidden" name="startDate" id="create-date-alt">
                        </div>
                        <div class="form-group col-md-3">
                            <label class="control-label">تا تاریخ</label>
                            <input class="form-control transactions-date" type="text" >
                            <input type="hidden" name="endDate" id="transactions-date-alt">
                        </div>
                        <!-- <div class="form-group col-md-3">
                            <label class="control-label">وضعیت</label>
                            <input class="form-control" type="text" >
                        </div> -->
                    </div>
                </form>
            </div>
            <div class="tile-footer">
                <button class="btn btn-primary" type="button" id="formFilterSubmit"><i
                        class="fa fa-fw fa-lg fa-search"></i>جستجو</button>&nbsp;&nbsp;&nbsp;
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <table class="table table-hover table-bordered" id="transactions-table" style="width: 100%;">
                    <thead>
                        <tr>
                            <th>تاریخ ایجاد</th>
                            <th>مبلغ</th>
                            <th>تاریخ ارسال به درگاه</th>
                            <th>شناسه پرداخت</th>
                            <th>کدپیگیری</th>
                            <th>وضعیت</th>
                            <th>توضیحات</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js%}
<script type="text/javascript" src="{% static 'dashboard/js/plugins/sweetalert.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/utility.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/dropzone.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/select2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/dataTables.bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/persian-datatable.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/persian-date.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/plugins/persian-datepicker.min.js' %}"></script>
<script>
    $(() => {

        $('.transactions-date').persianDatepicker({
            observer: true,
            format: 'YYYY/MM/DD',
            altField: '#transactions-date-alt'
        });
        
        $('.create-date').persianDatepicker({
            observer: true,
            format: 'YYYY/MM/DD',
            altField: '#create-date-alt'
        });

        var transactionsTable = $('#transactions-table').DataTable({
            paging: true,
            pageLength: 50,
            searching: true,
            fixedColumns: true,
            serverSide: true,
            ajax:{
                url: "{% url 'payment:ajax_invoice_get_all' %}",
                data: (data) => {
                    let formData = $('#filterForm').serialize()
                    data = new URLSearchParams({
                        start: data.start,
                        length: data.length,
                        search: data.search.value,
                        csrfmiddlewaretoken: "{{ csrf_token }}"
                    }).toString()
                    return data + '&' + formData
                },
                type: 'POST'
            },
            columns: [
                {
                    data: 'createAt',
                    render: (date) => {
                        return new Date(date).toLocaleDateString('fa-IR')
                    }
                },
                {
                    data: 'amount'
                },
                {
                    data: 'shippingDate',
                    render: (date) => {
                        if(date == null)
                            return '<a href="#" class="sm pay-now">(هم اکنون پرداخت کنید)</a>'
                        return new Date(date).toLocaleDateString('fa-IR')
                    }
                },
                {
                    data: 'authority',
                    className: "authority"
                },
                {
                    data: 'referenceId'
                },
                {
                    data: 'status',
                    render: (status) => {
                        s = {
                            {% for choice in choices %}
                                {{choice.0}}: "{{choice.1}}",
                            {% endfor %}
                        }
                        return s[status]
                    }
                },
                {
                    data: 'description'
                }
            ],
            language: datatablePersianLang,
        })

        $('#formFilterSubmit').click(event => {
            transactionsTable.ajax.reload()
        })

        $('#transactions-table').on('click', 'a.pay-now', (e) => {
            let authority = $(e.target).parent().parent().find('.authority').html()
            window.location.href = "{% url 'payment:pay' '0' %}" + authority
        })

    })
</script>
{% endblock %}